# Generated by Django 4.2.11 on 2024-03-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
