# Generated by Django 4.2.11 on 2024-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_author_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions ...'),
        ),
    ]
