start:
	python manage.py runserver
migrate:
	python manage.py migrate
makemigrations:
	python manage.py makemigrations
install-dev:
	pip install -r requirements/dev.txt
install-base:
	pip install -r requirements/base.txt